### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by ypriverol** [fickludd/dinosaur#3]
Hi guys:
 Are you still active with this project?
REgards

**Comment by kerner1000** [comment]
Apparently not, which is a shame, I think this project got some potential..

**Comment by fickludd** [comment]
Hi both,

I'm not actively developing this program. It filled the purpose of feature detection for our in-house needs, and since I've become a full-time software dev. outside science. If you have feature or bug fixes for please create pull request towards this repo, and I will gladly review and eventually merge them.

**Comment by flevander** [comment]
Please also report bugs, and we'll do our best to resolve!

**Comment by flevander** [comment]
Question answered
